(setf hp-kb '(
(list
(make-relation* :ent1 'Remus-Lupin :ent2 'defence-against-the-dark-arts-classroom :rel 'been-in)
(make-relation* :ent1 'greenhouses :ent2 'hogwarts-grounds :rel 'is-in)
(make-relation* :ent1 'Severus-Snape :ent2 'cokeworth :rel 'been-in)
(make-relation* :ent1 'Dolores-Umbridge :ent2 'mcgonagalls-office :rel 'been-in)
(make-relation* :ent1 'Severus-Snape :ent2 'third-floor-corridor :rel 'been-in)
(make-relation* :ent1 'Minerva-McGonagall :ent2 'gryffindor-common-room :rel 'been-in)
(make-relation* :ent1 'gryffindor-tower :ent2 'hogwarts-school-of-witchcraft-and-wizardry :rel 'is-in)
(make-relation* :ent1 'majorca :ent2 'spain :rel 'is-in)
(make-relation* :ent1 'hogwarts-quidditch-pitch-stadium :ent2 'hogwarts-grounds :rel 'is-in)
(make-relation* :ent1 'Hermione-Granger :ent2 'hospital-wing :rel 'been-in)
)
(list
(make-relation* :ent1 'library :ent2 'hogwarts-fourth-floor :rel 'is-in)
(make-relation* :ent1 'Gregory-Goyle :ent2 'slytherin-common-room :rel 'been-in)
(make-relation* :ent1 'Ron-Weasley :ent2 'hospital-wing :rel 'been-in)
(make-relation* :ent1 'Lord-Voldemort :ent2 'azkaban :rel 'been-in)
(make-relation* :ent1 'Ernie-Macmillan :ent2 'potions-classroom :rel 'been-in)
(make-relation* :ent1 'Horace-Slughorn :ent2 'potions-classroom :rel 'been-in)
(make-relation* :ent1 'Vincent-Crabbe :ent2 'slytherin-common-room :rel 'been-in)
(make-relation* :ent1 'england :ent2 'great-britain :rel 'is-in)
(make-relation* :ent1 'Hermione-Granger :ent2 'hospital-wing :rel 'been-in)
(make-relation* :ent1 'staff-room :ent2 'hogwarts-ground-floor :rel 'is-in)
)
(list
(make-relation* :ent1 'hogwarts-seventh-floor :ent2 'hogwarts-school-of-witchcraft-and-wizardry :rel 'is-in)
(make-relation* :ent1 'Madam-Marsh :ent2 'aberdeen :rel 'been-in)
(make-relation* :ent1 'Parvati-Patil :ent2 'divination-classroom :rel 'been-in)
(make-relation* :ent1 'heads-office :ent2 'hogwarts-seventh-floor :rel 'is-in)
(make-relation* :ent1 'Magorian :ent2 'forbidden-forest :rel 'been-in)
(make-relation* :ent1 'hogsmeade :ent2 'scotland :rel 'is-in)
(make-relation* :ent1 'Harry-Potter :ent2 'anglesey :rel 'been-in)
(make-relation* :ent1 'Madam-Puddifoot :ent2 'hogsmeade :rel 'been-in)
(make-relation* :ent1 'Fang :ent2 'hagrids-hut :rel 'been-in)
(make-relation* :ent1 'Ron-Weasley :ent2 'gryffindor-common-room :rel 'been-in)
)
(list
(make-relation* :ent1 'hogwarts-fourth-floor :ent2 'hogwarts-school-of-witchcraft-and-wizardry :rel 'is-in)
(make-relation* :ent1 'Violet :ent2 'antechamber-of-the-great-hall :rel 'been-in)
(make-relation* :ent1 'defence-against-the-dark-arts-classroom :ent2 'hogwarts-first-floor :rel 'is-in)
(make-relation* :ent1 'hogwarts-ground-floor :ent2 'hogwarts-school-of-witchcraft-and-wizardry :rel 'is-in)
(make-relation* :ent1 'Severus-Snape :ent2 'heads-office :rel 'been-in)
(make-relation* :ent1 'Hermione-Granger :ent2 'potions-classroom :rel 'been-in)
(make-relation* :ent1 'Fred-Weasley :ent2 'gryffindor-common-room :rel 'been-in)
(make-relation* :ent1 'Aragog :ent2 'forbidden-forest :rel 'been-in)
(make-relation* :ent1 'Luc-Millefeuille :ent2 'beauxbatons-academy-of-magic :rel 'been-in)
(make-relation* :ent1 'forbidden-forest :ent2 'hogwarts-grounds :rel 'is-in)
)
(list
(make-relation* :ent1 'minsk :ent2 'belarus :rel 'is-in)
(make-relation* :ent1 'Dobby :ent2 'room-of-requirement :rel 'been-in)
(make-relation* :ent1 'Salazar-Slytherin :ent2 'chamber-of-secrets :rel 'been-in)
(make-relation* :ent1 'Remus-Lupin :ent2 'defence-against-the-dark-arts-teachers-office :rel 'been-in)
(make-relation* :ent1 'hogwarts-fourth-floor :ent2 'hogwarts-school-of-witchcraft-and-wizardry :rel 'is-in)
(make-relation* :ent1 'Harry-Potter :ent2 'hagrids-hut :rel 'been-in)
(make-relation* :ent1 'Ernie-Macmillan :ent2 'potions-classroom :rel 'been-in)
(make-relation* :ent1 'Rubeus-Hagrid :ent2 'minsk :rel 'been-in)
(make-relation* :ent1 'Gabrielle-Delacour :ent2 'beauxbatons-academy-of-magic :rel 'been-in)
(make-relation* :ent1 'Harry-Potter :ent2 'birmingham :rel 'been-in)
)
(list
(make-relation* :ent1 'hogwarts-third-floor :ent2 'hogwarts-school-of-witchcraft-and-wizardry :rel 'is-in)
(make-relation* :ent1 'potions-classroom :ent2 'dungeons :rel 'is-in)
(make-relation* :ent1 'Ginny-Weasley :ent2 'gryffindor-common-room :rel 'been-in)
(make-relation* :ent1 'Percy-Weasley :ent2 'gryffindor-common-room :rel 'been-in)
(make-relation* :ent1 'Argus-Filch :ent2 'room-of-requirement :rel 'been-in)
(make-relation* :ent1 'Dolores-Umbridge :ent2 'defence-against-the-dark-arts-classroom :rel 'been-in)
(make-relation* :ent1 'hogwarts-ground-floor :ent2 'hogwarts-school-of-witchcraft-and-wizardry :rel 'is-in)
(make-relation* :ent1 'hagrids-hut :ent2 'hogwarts-grounds :rel 'is-in)
(make-relation* :ent1 'forbidden-forest :ent2 'hogwarts-grounds :rel 'is-in)
(make-relation* :ent1 'Lord-Voldemort :ent2 'azkaban :rel 'been-in)
)
(list
(make-relation* :ent1 'Madam-Puddifoot :ent2 'hogsmeade :rel 'been-in)
(make-relation* :ent1 'Alecto-Carrow :ent2 'ravenclaw-common-room :rel 'been-in)
(make-relation* :ent1 'Antonin-Dolohov :ent2 'azkaban :rel 'been-in)
(make-relation* :ent1 'cairo :ent2 'egypt :rel 'is-in)
(make-relation* :ent1 'romania :ent2 'europe :rel 'is-in)
(make-relation* :ent1 'Aberforth-Dumbledore :ent2 'hogsmeade :rel 'been-in)
(make-relation* :ent1 'Fang :ent2 'forbidden-forest :rel 'been-in)
(make-relation* :ent1 'dungeons :ent2 'hogwarts-school-of-witchcraft-and-wizardry :rel 'is-in)
(make-relation* :ent1 'Helena-Ravenclaw :ent2 'ravenclaw-common-room :rel 'been-in)
(make-relation* :ent1 'Bane :ent2 'forbidden-forest :rel 'been-in)
)
))
